<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php /** @TODO: only logged in customers must be able to make a request. Show login form on button click */ ?>
<div data-bind="scope: 'personalDiscountRequestButton'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "personalDiscountRequestButton": {
                        "component": "DVCampus_PersonalDiscount_formOpenButton"
                    }
                }
            }
        }
    }
</script>
