<?php
/**
 * @var \DVCampus\PersonalDiscount\Block\Product\View\DiscountRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getData('product');
// Show form in modal window by default
$isModal = $block->hasData('is_modal') ? (int) $block->getData('is_modal') : 1;
?>
<div class="dv-campus-personal-discount-request">
    <form class="form dv-campus-personal-discount-form"
          action="/errors/404.php"
          onsubmit="return false;"
          method="post"
          data-mage-init='{"DVCampus_PersonalDiscount_form":{
              "action": "<?= $escaper->escapeHtmlAttr($block->getUrl('dvcampus_personal_discount/index/request')) ?>",
              "isModal": <?= $escaper->escapeHtmlAttr($isModal) ?>
          }}'
    >
        <fieldset class="fieldset">
            <legend class="legend">
                <span><?= $escaper->escapeHtml(__('Discount Request')) ?></span>
            </legend>
            <br/>
            <div class="field name required">
                <label class="label" for="name">
                    <span><?= $escaper->escapeHtml(__('Name')) ?></span>
                </label>
                <div class="control">
                    <input name="name"
                           title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                           class="input-text"
                           type="text"
                           data-validate="{required:true}"
                    />
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email">
                    <span><?= $escaper->escapeHtml(__('Email')) ?></span>
                </label>
                <div class="control">
                    <input name="email"
                           title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text"
                           type="email"
                           data-validate="{required:true, 'validate-email':true}"
                    />
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email">
                    <span><?= $escaper->escapeHtml(__('Message')) ?></span>
                </label>
                <div class="control">
                    <textarea name="message"
                              title="<?= $escaper->escapeHtmlAttr(__('Message')) ?>"
                              class="input-text"
                              data-validate="{required:true}"
                    ></textarea>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden"
                       name="product_id"
                       value="<?= $escaper->escapeHtmlAttr((int) $product->getId()) ?>"
                />
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Send Request')) ?>"
                        class="action submit primary"
                >
                    <span><?= $escaper->escapeHtml(__('Send Request')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
